name : my-workflow

on: 
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
        - name: "fork job"
          run: echo "Raj Forked!!!!!!!!!!!!!!1"
    
      
